Program = "music-player-use-go-vue"

[mysql]
ip = "gocloudcoder.com"
port = "3306"
username = "music-player"
password = "000000"
database = "music-player"

[redis]
ip = "gocloudcoder.com"
port = "6379"


