Program = "music-player-use-go-vue"

[mysql]
ip = "nj-jay.com"
port = "3306"
username = "mysql_nj_jay_com"
password = "000000"
database = "mysql_nj_jay_com"

[redis]
ip = "nj-jay.com"
port = "6379"


