  version: "2.0"

  services:
    server:
      build: server
      container_name: music-player-server
      restart: always
      ports:
        - '8082:8082'
      depends_on:
        - db-mysql
        - db-redis
    db-mysql:
      image: mysql:5.7
      container_name: music-player-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "123456"
        MYSQL_DATABASE: "music-player"
      expose:
        - 3306
    db-redis:
      image: redis:latest
      container_name: music-player-redis
      restart: always
      expose:
        - 6379
    web:
      build: web
      container_name: music-player-web
      restart: always
      ports:
        - 80:80
      depends_on:
        - server
